language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12.x"
  - "0.11.x"
  - "0.10.x"

notifications:
  email:
    on_success: always
    on_failure: always

after_script: "cat ./coverage/lcov.info | coveralls"

aftersuccess:
  - coveralls
