language: node_js

node_js:
  - "6"
  - "4"
  - "0.12.0"

sudo: false

notifications:
  email:
    on_success: always
    on_failure: always

after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"

aftersuccess:
