language: node_js

node_js:
  - "6"
  - "4"
  - "0.12.0"
  - "0.10.0"

notifications:
  email:
    on_success: always
    on_failure: always

after_script: "cat ./coverage/lcov.info | coveralls"

aftersuccess:
  - coveralls
